services:
  - type: web
    name: lilas-nutrition
    env: static
    buildCommand: |
      flutter/bin/flutter config --enable-web
      flutter/bin/flutter build web --release
    staticPublishPath: build/web
    envVars:
      - key: FLUTTER_VERSION
        value: 3.27.0